
log: yes
save_model: no
log_images: yes

gpu: cuda:1

dice_loss_weight: 1

early_stopping:
  patience: 7
  delta: 0
  path: /home/paulw/projects/mri-expert/checkpoint.pt

wandb:
  #dir: 
  entity: pfrwilson
  project: mri-expert
  name: Test_run_0 

data:
  root: /home/paulw/data/TrainingData
  batch_size: 16
  split_seed: 0
  use_augmentations: yes
  preprocessor_kwargs: {}

optim:
  lr: 1e-5
  scheduler: null

training:
  num_epochs: 200
  accumulate_grad_batches: 4

