
log: yes
save_model: no
log_images: yes

gpu: cuda:1

dice_loss_weight: .5

early_stopping:
  patience: 10
  delta: 0

wandb:
  #dir: 
  entity: pfrwilson
  project: mri-expert

data:
  root: /home/paulw/data/TrainingData
  batch_size: 16
  split_seed: 0
  use_augmentations: yes
  preprocessor_kwargs: {}

optim:
  lr: 1e-4          # best 1e-4
  scheduler: null

training:
  num_epochs: 200
  accumulate_grad_batches: 1    # best 1

