
log: no
save_model: no
log_images: no

wandb:
  #name: 
  #dir: 
  entity: pfrwilson
  project: mri-expert
  name: null

data:
  root: /Users/paulwilson/projects/medical_imaging/prostate-segmentation/TrainingData
  batch_size: 8
  split_seed: 0
  val_size: 5
  target_size: 224
  use_augmentations: yes
  preprocessor_kwargs: {}


optim:
  lr: 1e-3
  scheduler: cosine

training:
  num_epochs: 1
  accumulate_grad_batches: 1